import type { Issuer } from "./issuer-columns"

export const issuerData: Issuer[] = [
  {
    id: "728ed52f",
    name: "Metro General Hospital",
    type: "Hospital",
    email: "admin@metrogeneral.com",
    status: "active",
    createdAt: "2024-01-10",
    verifiedAt: "2024-01-12",
    location: "New York, NY",
  },
  {
    id: "489e1d42",
    name: "Dr. Sarah Johnson",
    type: "Doctor",
    email: "sarah.j@healthcare.com",
    status: "pending",
    createdAt: "2024-02-15",
    verifiedAt: null,
    location: "Los Angeles, CA",
  },
  {
    id: "9a8b7c6d",
    name: "Central Pharmacy",
    type: "Pharmacy",
    email: "central@pharmacy.com",
    status: "active",
    createdAt: "2024-01-20",
    verifiedAt: "2024-01-22",
    location: "Chicago, IL",
  },
  {
    id: "5e6f7g8h",
    name: "Wellness Medical Center",
    type: "Hospital",
    email: "info@wellnessmed.com",
    status: "active",
    createdAt: "2024-01-05",
    verifiedAt: "2024-01-07",
    location: "Houston, TX",
  },
  {
    id: "2b3c4d5e",
    name: "Dr. Michael Chen",
    type: "Doctor",
    email: "m.chen@healthcare.com",
    status: "suspended",
    createdAt: "2023-12-01",
    verifiedAt: "2023-12-03",
    location: "San Francisco, CA",
  },
  {
    id: "9h8g7f6e",
    name: "HealthFirst Pharmacy",
    type: "Pharmacy",
    email: "contact@healthfirst.com",
    status: "active",
    createdAt: "2024-01-15",
    verifiedAt: "2024-01-17",
    location: "Boston, MA",
  },
  {
    id: "4d5e6f7g",
    name: "City Medical Group",
    type: "Hospital",
    email: "admin@citymedical.com",
    status: "active",
    createdAt: "2024-02-01",
    verifiedAt: "2024-02-03",
    location: "Miami, FL",
  },
  {
    id: "1a2b3c4d",
    name: "Dr. Emily Wilson",
    type: "Doctor",
    email: "e.wilson@healthcare.com",
    status: "pending",
    createdAt: "2024-02-10",
    verifiedAt: null,
    location: "Seattle, WA",
  },
  {
    id: "7k8l9m0n",
    name: "MediCare Pharmacy",
    type: "Pharmacy",
    email: "info@medicare-pharm.com",
    status: "active",
    createdAt: "2024-01-25",
    verifiedAt: "2024-01-27",
    location: "Denver, CO",
  },
  {
    id: "3p4q5r6s",
    name: "Regional Health Center",
    type: "Hospital",
    email: "contact@regionalhc.com",
    status: "active",
    createdAt: "2024-01-30",
    verifiedAt: "2024-02-01",
    location: "Phoenix, AZ",
  },
]

